version: '3.8'

services:
  memcached:
    build: .
    ports:
      - "11211:11211"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 10s
      retries: 3